#!/bin/bash

# Usage example: $0 factorial
# to build and run factorial.jar from factorial.m

main_module="$1"
jmlib="$HOME/Library/Mercury/lib/mercury/lib/java"


mmc --make --infer-all --gc none --java "$main_module"
java -cp "$main_module".jar:"$jmlib"/mer_std.jar:"$jmlib"/mer_rt.jar jmercury."$main_module"

